#!/bin/sh

# Move into our HOME directory
cd
root=$(pwd)

DATE=$(date +"%y%m%d")
SRCPATH="/Volumes/DR-100MK2/MUSIC"
DSTPATH="$root/Sermons"

FULL="$DSTPATH/Full"
TRACKS="$DSTPATH/Tracks"

test ! -d $SRCPATH && {
  echo "Error: Digital Recorder is not mounted."
  exit 1
}

test ! -d $DSTPATH && {
  echo "Error: For some reason we are missing our Sermons directory $DSTPATH, bailing..."
  exit 1
}

for file in $(ls $SRCPATH)
do
  ### Copy our full sermon to Dropbox
  test ! -f $FULL/$file && {
    echo "Copying $SRCPATH/$file to $FULL/$file...\c"
    cp $SRCPATH/$file $FULL/$file
    echo "done."
  }

  ### Split our sermon into minute tracks
  filename=$(echo $file | cut -d. -f1)
  test ! -d $TRACKS/$filename && {
    ### Creating directory for $filename
    mkdir -p $TRACKS/$filename
    cd $FULL/$file
    mp3splt -f -t 1.0 -a -d $TRACKS/$filename $file
    if [ $? -ne 0 ]
    then echo "Error: mp3splt didn't work."
    fi
  }
done
